# 等待测试用例
wait_case:
  1992: [src.testcase.case.GNAPP_VERSION.GNAPP_VERSION_001, 当前版本为最新版本，页面信息检查]
  
  1889: [src.testcase.case.GNAPP_LOGIN.GNAPP_LOGIN_001, 登录页面—新用户注册页面跳转]
  1890: [src.testcase.case.GNAPP_LOGIN.GNAPP_LOGIN_002, 登录页面—忘记密码页面跳转]
  1891: [src.testcase.case.GNAPP_LOGIN.GNAPP_LOGIN_003, 登录页面—登录功能检查]
  1903: [src.testcase.case.GNAPP_LOGIN.GNAPP_LOGIN_004, 登录页面—成功登录后杀掉APP，再次开启APP的状态查看]
  1900: [src.testcase.case.GNAPP_LOGIN.GNAPP_LOGIN_005, 登录页面—成功登录后注销账号，再次进入登录页面查看]
  1899: [src.testcase.case.GNAPP_LOGIN.GNAPP_LOGIN_006, 登录页面—错误密码输入次数超过5次后，账号锁定1分钟验证]
  1897: [src.testcase.case.GNAPP_LOGIN.GNAPP_LOGIN_007, 登录页面—错误密码，登录提示信息检查]
  1898: [src.testcase.case.GNAPP_LOGIN.GNAPP_LOGIN_008, 登录页面—密码输入超过5次后，信息检查]
  1896: [src.testcase.case.GNAPP_LOGIN.GNAPP_LOGIN_009, 登录页面—密码为空，登录提示信息检查]
  1895: [src.testcase.case.GNAPP_LOGIN.GNAPP_LOGIN_010, 登录页面—位数错误的数字账号，登录提示信息检查]
  1894: [src.testcase.case.GNAPP_LOGIN.GNAPP_LOGIN_011, 登录页面—未注册的手机号码，登录提示信息检查]
  1893: [src.testcase.case.GNAPP_LOGIN.GNAPP_LOGIN_012, 登录页面—账号为空，登录提示信息检查]
  1892: [src.testcase.case.GNAPP_LOGIN.GNAPP_LOGIN_013, 登录页面—无效账号，登录提示信息检查]
  
  1965: [src.testcase.case.GNAPP_ACCOUNT_SETTINGS.GNAPP_ACCOUNT_SETTINGS_001, 修改密码页面，返回"按钮功能检查"]
  1972: [src.testcase.case.GNAPP_ACCOUNT_SETTINGS.GNAPP_ACCOUNT_SETTINGS_002, 密码修改后页面跳转确认]
  1973: [src.testcase.case.GNAPP_ACCOUNT_SETTINGS.GNAPP_ACCOUNT_SETTINGS_003, 退出当前账号后，取消按钮功能检查]
  1974: [src.testcase.case.GNAPP_ACCOUNT_SETTINGS.GNAPP_ACCOUNT_SETTINGS_004, 退出当前账号后，确定按钮功能检查]
  1970: [src.testcase.case.GNAPP_ACCOUNT_SETTINGS.GNAPP_ACCOUNT_SETTINGS_005, 密码修改页面，旧密码输入错误，提示信息检查]
  1946: [src.testcase.case.GNAPP_ACCOUNT_SETTINGS.GNAPP_ACCOUNT_SETTINGS_006, 点击昵称"按钮，功能检查"]
  1948: [src.testcase.case.GNAPP_ACCOUNT_SETTINGS.GNAPP_ACCOUNT_SETTINGS_007, 昵称为空时，功能检查]
  1949: [src.testcase.case.GNAPP_ACCOUNT_SETTINGS.GNAPP_ACCOUNT_SETTINGS_008, 昵称修改成功，页面信息检查]
  1969: [src.testcase.case.GNAPP_ACCOUNT_SETTINGS.GNAPP_ACCOUNT_SETTINGS_009, 密码修改页面，新密码与确认密码不一致，提示信息检查]
  1968: [src.testcase.case.GNAPP_ACCOUNT_SETTINGS.GNAPP_ACCOUNT_SETTINGS_010, 密码修改页面，确认密码为空，提示信息检查]
  1967: [src.testcase.case.GNAPP_ACCOUNT_SETTINGS.GNAPP_ACCOUNT_SETTINGS_011, 密码修改页面，新密码与确认密码均为空，提示信息检查]
  1966: [src.testcase.case.GNAPP_ACCOUNT_SETTINGS.GNAPP_ACCOUNT_SETTINGS_012, 密码修改页面，旧密码为空，提示信息检查]
  1947: [src.testcase.case.GNAPP_ACCOUNT_SETTINGS.GNAPP_ACCOUNT_SETTINGS_013, 昵称长度16位验证，功能检查]
  
  1888: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_001, 注册页面-已有账户登录按钮，跳转页面检查]
  1885: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_002, 注册页面-正确的用户名和密码，空的验证码，注册验证]
  1884: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_003, 注册页面-正确的用户名和密码，验证码大于6位，注册验证]
  1883: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_004, 注册页面-正确的用户名和密码，错误的6位数字验证码，注册验证]
  1882: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_005, 注册页面-正确的用户名和密码，小于6位数字验证码，注册验证]
  1881: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_006, 注册页面-验证码为特殊字符时，提示信息检查]
  1880: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_007, 注册页面-验证码为中文字符时，提示信息检查]
  1879: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_008, 注册页面-验证码为英文字符时，提示信息检查]
  1866: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_009, 注册页面-密码长度大于16位，注册检查]
  1840: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_010, 注册页面-密码长度小于6位，注册检查]
  1838: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_011, 注册页面-用户名长度小于11位，提示信息检查]
  1826: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_012, 注册页面-用户名长度大于11位，提示信息检查]
  1825: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_013, 注册页面-用户名为空，注册验证]
  1824: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_014, 注册页面-用户名为英文字符时，提示信息检查]
  1772: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_015, 注册页面-用户名为特殊字符时，提示信息检查]
  1771: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_016, 注册页面-用户名为中文字符时，提示信息检查]
  1769: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_017, 注册页面-用户名为数字时(非正确的手机号码)，提示信息检查]
  1768: [src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_018, 注册页面-已经注册过的用户名，再次注册验证]
  
  1904: [src.testcase.case.GNAPP_FORGET_PASSWORD.GNAPP_FORGET_PASSWORD_001, 忘记密码页面-点击"返回"按钮，页面检查]
  1909: [src.testcase.case.GNAPP_FORGET_PASSWORD.GNAPP_FORGET_PASSWORD_002, 忘记密码页面-未注册账户检测]
  1907: [src.testcase.case.GNAPP_FORGET_PASSWORD.GNAPP_FORGET_PASSWORD_003, 忘记密码页面-点击返回登入界面"按钮，页面检查"]
  
  1922: [src.testcase.case.GNAPP_MESSAGE_CLASSIFY.GNAPP_MESSAGE_CLASSIFY_001, 消息分类页面信息检查]
  1926: [src.testcase.case.GNAPP_MESSAGE_CLASSIFY.GNAPP_MESSAGE_CLASSIFY_002, 消息设置页面，清空活动历时消息功能检查]
  1927: [src.testcase.case.GNAPP_MESSAGE_CLASSIFY.GNAPP_MESSAGE_CLASSIFY_003, 消息设置页面，清空设备历时消息功能检查]
  1925: [src.testcase.case.GNAPP_MESSAGE_CLASSIFY.GNAPP_MESSAGE_CLASSIFY_004, 消息设置页面信息检查]
  1924: [src.testcase.case.GNAPP_MESSAGE_CLASSIFY.GNAPP_MESSAGE_CLASSIFY_005, 消息分类页面，选择多个设备后的消息内容检查]
  
  1773: [src.testcase.case.GNAPP_DEVICE_PAGE.GNAPP_DEVICE_PAGE_001, 默认页面信息检查]
  1798: [src.testcase.case.GNAPP_DEVICE_PAGE.GNAPP_DEVICE_PAGE_002, 设备配网过程中，返回按钮功能检查]
  1799: [src.testcase.case.GNAPP_DEVICE_PAGE.GNAPP_DEVICE_PAGE_003, 设备配网过程中，弹出终止配网提示框，取消按钮功能检查]
  1800: [src.testcase.case.GNAPP_DEVICE_PAGE.GNAPP_DEVICE_PAGE_004, 设备配网过程中，弹出终止配网提示框，确定按钮功能检查]
  1807: [src.testcase.case.GNAPP_DEVICE_PAGE.GNAPP_DEVICE_PAGE_005, 配网失败页面信息检查]
  1808: [src.testcase.case.GNAPP_DEVICE_PAGE.GNAPP_DEVICE_PAGE_006, 配网失败页面，取消按钮功能检查]
  
  1976: [src.testcase.case.GNAPP_FEED_BACK.GNAPP_FEED_BACK_001, 返回按钮功能检查]
  
  1975: [src.testcase.case.GNAPP_USING_HELP.GNAPP_USING_HELP_001, 返回按钮功能确认]
  
  1986: [src.testcase.case.GNAPP_THEME_STYLE.GNAPP_THEME_STYLE_001, 返回按钮功能检查]
  1990: [src.testcase.case.GNAPP_THEME_STYLE.GNAPP_THEME_STYLE_002, 切换为紫色后，查看风格]
  1989: [src.testcase.case.GNAPP_THEME_STYLE.GNAPP_THEME_STYLE_003, 切换为橙色后，查看风格]
  1988: [src.testcase.case.GNAPP_THEME_STYLE.GNAPP_THEME_STYLE_004, 切换为红色后，查看风格]
  1987: [src.testcase.case.GNAPP_THEME_STYLE.GNAPP_THEME_STYLE_005, 切换为绿色后，查看风格]
  1985: [src.testcase.case.GNAPP_THEME_STYLE.GNAPP_THEME_STYLE_006, 页面检查]
