#自动化测试用例对照表:
case_table:
  1965:
    'CASE_MODULE': ['账户设置']
    'CODE_ID': ['GNAppAccountSettings1']
    'CASE_NAME': ['修改密码页面，返回"按钮功能检查"']
    'CODE_PATH': ['./src/testcase/case/GNAPP_ACCOUNT_SETTINGS/GNAPP_ACCOUNT_SETTINGS_001.py']
  1972:
    'CASE_MODULE': ['账户设置']
    'CODE_ID': ['GNAppAccountSettings2']
    'CASE_NAME': ['密码修改后页面跳转确认']
    'CODE_PATH': ['./src/testcase/case/GNAPP_ACCOUNT_SETTINGS/GNAPP_ACCOUNT_SETTINGS_002.py']
  1973:
    'CASE_MODULE': ['账户设置']
    'CODE_ID': ['GNAppAccountSettings3']
    'CASE_NAME': ['退出当前账号后，取消按钮功能检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_ACCOUNT_SETTINGS/GNAPP_ACCOUNT_SETTINGS_003.py']
  1974:
    'CASE_MODULE': ['账户设置']
    'CODE_ID': ['GNAppAccountSettings4']
    'CASE_NAME': ['退出当前账号后，确定按钮功能检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_ACCOUNT_SETTINGS/GNAPP_ACCOUNT_SETTINGS_004.py']
  1970:
    'CASE_MODULE': ['账户设置']
    'CODE_ID': ['GNAppAccountSettings5']
    'CASE_NAME': ['密码修改页面，旧密码输入错误，提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_ACCOUNT_SETTINGS/GNAPP_ACCOUNT_SETTINGS_005.py']
  1946:
    'CASE_MODULE': ['账户设置']
    'CODE_ID': ['GNAppAccountSettings6']
    'CASE_NAME': ['点击昵称"按钮，功能检查"']
    'CODE_PATH': ['./src/testcase/case/GNAPP_ACCOUNT_SETTINGS/GNAPP_ACCOUNT_SETTINGS_006.py']
  1948:
    'CASE_MODULE': ['账户设置']
    'CODE_ID': ['GNAppAccountSettings7']
    'CASE_NAME': ['昵称为空时，功能检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_ACCOUNT_SETTINGS/GNAPP_ACCOUNT_SETTINGS_007.py']
  1949:
    'CASE_MODULE': ['账户设置']
    'CODE_ID': ['GNAppAccountSettings8']
    'CASE_NAME': ['昵称修改成功，页面信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_ACCOUNT_SETTINGS/GNAPP_ACCOUNT_SETTINGS_008.py']
  1969:
    'CASE_MODULE': ['账户设置']
    'CODE_ID': ['GNAppAccountSettings9']
    'CASE_NAME': ['密码修改页面，新密码与确认密码不一致，提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_ACCOUNT_SETTINGS/GNAPP_ACCOUNT_SETTINGS_009.py']
  1968:
    'CASE_MODULE': ['账户设置']
    'CODE_ID': ['GNAppAccountSettings10']
    'CASE_NAME': ['密码修改页面，确认密码为空，提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_ACCOUNT_SETTINGS/GNAPP_ACCOUNT_SETTINGS_010.py']
  1967:
    'CASE_MODULE': ['账户设置']
    'CODE_ID': ['GNAppAccountSettings11']
    'CASE_NAME': ['密码修改页面，新密码与确认密码均为空，提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_ACCOUNT_SETTINGS/GNAPP_ACCOUNT_SETTINGS_011.py']
  1966:
    'CASE_MODULE': ['账户设置']
    'CODE_ID': ['GNAppAccountSettings12']
    'CASE_NAME': ['密码修改页面，旧密码为空，提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_ACCOUNT_SETTINGS/GNAPP_ACCOUNT_SETTINGS_012.py']
  1947:
    'CASE_MODULE': ['账户设置']
    'CODE_ID': ['GNAppAccountSettings13']
    'CASE_NAME': ['昵称长度16位验证，功能检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_ACCOUNT_SETTINGS/GNAPP_ACCOUNT_SETTINGS_013.py']
  1773:
    'CASE_MODULE': ['设备页']
    'CODE_ID': ['GNAppDevicePage1']
    'CASE_NAME': ['默认页面信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_DEVICE_PAGE/GNAPP_DEVICE_PAGE_001.py']
  1798:
    'CASE_MODULE': ['设备页']
    'CODE_ID': ['GNAppDevicePage2']
    'CASE_NAME': ['设备配网过程中，返回按钮功能检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_DEVICE_PAGE/GNAPP_DEVICE_PAGE_002.py']
  1799:
    'CASE_MODULE': ['设备页']
    'CODE_ID': ['GNAppDevicePage3']
    'CASE_NAME': ['设备配网过程中，弹出终止配网提示框，取消按钮功能检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_DEVICE_PAGE/GNAPP_DEVICE_PAGE_003.py']
  1800:
    'CASE_MODULE': ['设备页']
    'CODE_ID': ['GNAppDevicePage4']
    'CASE_NAME': ['设备配网过程中，弹出终止配网提示框，确定按钮功能检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_DEVICE_PAGE/GNAPP_DEVICE_PAGE_004.py']
  1807:
    'CASE_MODULE': ['设备页']
    'CODE_ID': ['GNAppDevicePage5']
    'CASE_NAME': ['配网失败页面信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_DEVICE_PAGE/GNAPP_DEVICE_PAGE_005.py']
  1808:
    'CASE_MODULE': ['设备页']
    'CODE_ID': ['GNAppDevicePage6']
    'CASE_NAME': ['配网失败页面，取消按钮功能检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_DEVICE_PAGE/GNAPP_DEVICE_PAGE_006.py']
  1976:
    'CASE_MODULE': ['意见反馈']
    'CODE_ID': ['GNAppFeedBack1']
    'CASE_NAME': ['返回按钮功能检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_FEED_BACK/GNAPP_FEED_BACK_001.py']
  1904:
    'CASE_MODULE': ['忘记密码']
    'CODE_ID': ['GNAppForgetPassword1']
    'CASE_NAME': ['忘记密码页面-点击"返回"按钮，页面检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_FORGET_PASSWORD/GNAPP_FORGET_PASSWORD_001.py']
  1909:
    'CASE_MODULE': ['忘记密码']
    'CODE_ID': ['GNAppForgetPassword2']
    'CASE_NAME': ['忘记密码页面-未注册账户检测']
    'CODE_PATH': ['./src/testcase/case/GNAPP_FORGET_PASSWORD/GNAPP_FORGET_PASSWORD_002.py']
  1907:
    'CASE_MODULE': ['忘记密码']
    'CODE_ID': ['GNAppForgetPassword3']
    'CASE_NAME': ['忘记密码页面-点击返回登入界面"按钮，页面检查"']
    'CODE_PATH': ['./src/testcase/case/GNAPP_FORGET_PASSWORD/GNAPP_FORGET_PASSWORD_003.py']
  1889:
    'CASE_MODULE': ['登录']
    'CODE_ID': ['GNAppLogin1']
    'CASE_NAME': ['登录页面—新用户注册页面跳转']
    'CODE_PATH': ['./src/testcase/case/GNAPP_LOGIN/GNAPP_LOGIN_001.py']
  1890:
    'CASE_MODULE': ['登录']
    'CODE_ID': ['GNAppLogin2']
    'CASE_NAME': ['登录页面—忘记密码页面跳转']
    'CODE_PATH': ['./src/testcase/case/GNAPP_LOGIN/GNAPP_LOGIN_002.py']
  1891:
    'CASE_MODULE': ['登录']
    'CODE_ID': ['GNAppLogin3']
    'CASE_NAME': ['登录页面—登录功能检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_LOGIN/GNAPP_LOGIN_003.py']
  1903:
    'CASE_MODULE': ['登录']
    'CODE_ID': ['GNAppLogin4']
    'CASE_NAME': ['登录页面—成功登录后杀掉APP，再次开启APP的状态查看']
    'CODE_PATH': ['./src/testcase/case/GNAPP_LOGIN/GNAPP_LOGIN_004.py']
  1900:
    'CASE_MODULE': ['登录']
    'CODE_ID': ['GNAppLogin5']
    'CASE_NAME': ['登录页面—成功登录后注销账号，再次进入登录页面查看']
    'CODE_PATH': ['./src/testcase/case/GNAPP_LOGIN/GNAPP_LOGIN_005.py']
  1899:
    'CASE_MODULE': ['登录']
    'CODE_ID': ['GNAppLogin6']
    'CASE_NAME': ['登录页面—错误密码输入次数超过5次后，账号锁定1分钟验证']
    'CODE_PATH': ['./src/testcase/case/GNAPP_LOGIN/GNAPP_LOGIN_006.py']
  1897:
    'CASE_MODULE': ['登录']
    'CODE_ID': ['GNAppLogin7']
    'CASE_NAME': ['登录页面—错误密码，登录提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_LOGIN/GNAPP_LOGIN_007.py']
  1898:
    'CASE_MODULE': ['登录']
    'CODE_ID': ['GNAppLogin8']
    'CASE_NAME': ['登录页面—密码输入超过5次后，信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_LOGIN/GNAPP_LOGIN_008.py']
  1896:
    'CASE_MODULE': ['登录']
    'CODE_ID': ['GNAppLogin9']
    'CASE_NAME': ['登录页面—密码为空，登录提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_LOGIN/GNAPP_LOGIN_009.py']
  1895:
    'CASE_MODULE': ['登录']
    'CODE_ID': ['GNAppLogin10']
    'CASE_NAME': ['登录页面—位数错误的数字账号，登录提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_LOGIN/GNAPP_LOGIN_010.py']
  1894:
    'CASE_MODULE': ['登录']
    'CODE_ID': ['GNAppLogin11']
    'CASE_NAME': ['登录页面—未注册的手机号码，登录提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_LOGIN/GNAPP_LOGIN_011.py']
  1893:
    'CASE_MODULE': ['登录']
    'CODE_ID': ['GNAppLogin12']
    'CASE_NAME': ['登录页面—账号为空，登录提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_LOGIN/GNAPP_LOGIN_012.py']
  1892:
    'CASE_MODULE': ['登录']
    'CODE_ID': ['GNAppLogin13']
    'CASE_NAME': ['登录页面—无效账号，登录提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_LOGIN/GNAPP_LOGIN_013.py']
  1922:
    'CASE_MODULE': ['消息']
    'CODE_ID': ['GNAppMessageClassify1']
    'CASE_NAME': ['消息分类页面信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_MESSAGE_CLASSIFY/GNAPP_MESSAGE_CLASSIFY_001.py']
  1926:
    'CASE_MODULE': ['消息']
    'CODE_ID': ['GNAppMessageClassify2']
    'CASE_NAME': ['消息设置页面，清空活动历时消息功能检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_MESSAGE_CLASSIFY/GNAPP_MESSAGE_CLASSIFY_002.py']
  1927:
    'CASE_MODULE': ['消息']
    'CODE_ID': ['GNAppMessageClassify3']
    'CASE_NAME': ['消息设置页面，清空设备历时消息功能检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_MESSAGE_CLASSIFY/GNAPP_MESSAGE_CLASSIFY_003.py']
  1925:
    'CASE_MODULE': ['消息']
    'CODE_ID': ['GNAppMessageClassify4']
    'CASE_NAME': ['消息设置页面信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_MESSAGE_CLASSIFY/GNAPP_MESSAGE_CLASSIFY_004.py']
  1924:
    'CASE_MODULE': ['消息']
    'CODE_ID': ['GNAppMessageClassify5']
    'CASE_NAME': ['消息分类页面，选择多个设备后的消息内容检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_MESSAGE_CLASSIFY/GNAPP_MESSAGE_CLASSIFY_005.py']
  1888:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister1']
    'CASE_NAME': ['注册页面-已有账户登录按钮，跳转页面检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_001.py']
  1885:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister2']
    'CASE_NAME': ['注册页面-正确的用户名和密码，空的验证码，注册验证']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_002.py']
  1884:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister3']
    'CASE_NAME': ['注册页面-正确的用户名和密码，验证码大于6位，注册验证']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_003.py']
  1883:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister4']
    'CASE_NAME': ['注册页面-正确的用户名和密码，错误的6位数字验证码，注册验证']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_004.py']
  1882:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister5']
    'CASE_NAME': ['注册页面-正确的用户名和密码，小于6位数字验证码，注册验证']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_005.py']
  1881:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister6']
    'CASE_NAME': ['注册页面-验证码为特殊字符时，提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_006.py']
  1880:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister7']
    'CASE_NAME': ['注册页面-验证码为中文字符时，提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_007.py']
  1879:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister8']
    'CASE_NAME': ['注册页面-验证码为英文字符时，提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_008.py']
  1866:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister9']
    'CASE_NAME': ['注册页面-密码长度大于16位，注册检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_009.py']
  1840:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister10']
    'CASE_NAME': ['注册页面-密码长度小于6位，注册检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_010.py']
  1838:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister11']
    'CASE_NAME': ['注册页面-用户名长度小于11位，提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_011.py']
  1826:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister12']
    'CASE_NAME': ['注册页面-用户名长度大于11位，提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_012.py']
  1825:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister13']
    'CASE_NAME': ['注册页面-用户名为空，注册验证']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_013.py']
  1824:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister14']
    'CASE_NAME': ['注册页面-用户名为英文字符时，提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_014.py']
  1772:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister15']
    'CASE_NAME': ['注册页面-用户名为特殊字符时，提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_015.py']
  1771:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister16']
    'CASE_NAME': ['注册页面-用户名为中文字符时，提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_016.py']
  1769:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister17']
    'CASE_NAME': ['注册页面-用户名为数字时(非正确的手机号码)，提示信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_017.py']
  1768:
    'CASE_MODULE': ['注册']
    'CODE_ID': ['GNAppRegister18']
    'CASE_NAME': ['注册页面-已经注册过的用户名，再次注册验证']
    'CODE_PATH': ['./src/testcase/case/GNAPP_REGISTER/GNAPP_REGISTER_018.py']
  1986:
    'CASE_MODULE': ['主题风格']
    'CODE_ID': ['GNAppThemeStyle1']
    'CASE_NAME': ['返回按钮功能检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_THEME_STYLE/GNAPP_THEME_STYLE_001.py']
  1990:
    'CASE_MODULE': ['主题风格']
    'CODE_ID': ['GNAppThemeStyle2']
    'CASE_NAME': ['切换为紫色后，查看风格']
    'CODE_PATH': ['./src/testcase/case/GNAPP_THEME_STYLE/GNAPP_THEME_STYLE_002.py']
  1989:
    'CASE_MODULE': ['主题风格']
    'CODE_ID': ['GNAppThemeStyle3']
    'CASE_NAME': ['切换为橙色后，查看风格']
    'CODE_PATH': ['./src/testcase/case/GNAPP_THEME_STYLE/GNAPP_THEME_STYLE_003.py']
  1988:
    'CASE_MODULE': ['主题风格']
    'CODE_ID': ['GNAppThemeStyle4']
    'CASE_NAME': ['切换为红色后，查看风格']
    'CODE_PATH': ['./src/testcase/case/GNAPP_THEME_STYLE/GNAPP_THEME_STYLE_004.py']
  1987:
    'CASE_MODULE': ['主题风格']
    'CODE_ID': ['GNAppThemeStyle5']
    'CASE_NAME': ['切换为绿色后，查看风格']
    'CODE_PATH': ['./src/testcase/case/GNAPP_THEME_STYLE/GNAPP_THEME_STYLE_005.py']
  1985:
    'CASE_MODULE': ['主题风格']
    'CODE_ID': ['GNAppThemeStyle6']
    'CASE_NAME': ['页面检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_THEME_STYLE/GNAPP_THEME_STYLE_006.py']
  1975:
    'CASE_MODULE': ['使用帮助']
    'CODE_ID': ['GNAppUsingHelp1']
    'CASE_NAME': ['返回按钮功能确认']
    'CODE_PATH': ['./src/testcase/case/GNAPP_USING_HELP/GNAPP_USING_HELP_001.py']
  1992:
    'CASE_MODULE': ['版本信息']
    'CODE_ID': ['GNAppVersion1']
    'CASE_NAME': ['当前版本为最新版本，页面信息检查']
    'CODE_PATH': ['./src/testcase/case/GNAPP_VERSION/GNAPP_VERSION_001.py']
