# 打开APP超时时间
open_app_timeout: 60
# 搜索设备超时时间
search_device_timeout: 60
# 操作响应超时时间
request_timeout: 30
# 离线恢复超时时间
offline_recovery_timeout: 10
# 程序操作等待时间
operate_wait_time: 0.1
# 滚轮滑动等待时间
roll_time:
  GN: 0.3
  AL: 0.3
  JD: 0.3
  HW: 0.3
# 待添加的设备Mac
MAC:
  JD:
    0: 'C4-11-E0-00-BE-F6'
  AL:
    0: 'C4:11:E0:00:00:00'
  HW:
    0: 'C4:11:E0:01:45:7F'
# 电量计量设备备注名
Elec_stat_mac: ['Elec_test_1', 'Elec_test_2', 'Elec_test_3', 'Elec_test_4', 'Elec_test_5', 'Elec_test_6', 'Elec_test_7', 'Elec_test_8', 'Elec_test_9', 'Elec_test_10']
# 错误密码
err_pwd: '31323334353637383930'
# wifi密码
wifi_pwd: '696f74313233343536'
# 待选择App
App:
  GN_Android:
    appPackage: 'com.iotbull.android.superapp'
    waitActivity: 'com.iotbull.android.superapp/.activitys.regist_login.LoginActivity'
    appActivity: 'com.iotbull.android.superapp.activitys.regist_login.SplashActivity'
  AL_iOS:
    bundleId: 'com.aliyun.alink'
  JD_Android:
    appPackage: 'com.jd.smart'
    waitActivity: 'com.jd.smart.activity.LoadingActivity'
    appActivity: 'com.jd.smart.activity.LoadingActivity'
  JD_iOS:
    bundleId: 'com.jd.smart'
  GN_iOS:
    bundleId: 'com.eamon.gongniu'
  AL_Android:
    appPackage: 'com.aliyun.alink'
    waitActivity: 'com.aliyun.alink.page.main.MainActivity'
    appActivity: 'com.aliyun.alink.page.main.MainActivity'
  HW_Android:
    appPackage: 'com.huawei.smarthome'
    waitActivity: 'com.huawei.smarthome.login.LauncherActivity'
    appActivity: 'com.huawei.smarthome.login.LauncherActivity'
# Toast消息
Toast:
  login_password_mistake: [40, 1570, 1040, 1750]
# 待测APP名称和设备名称
app_device_name:
  GN:
    app_name: "公牛智联"
    device_name: "GN-Y2010"
    app_ver: "V0.0.1.0623"
  AL:
    app_name: "阿里智能"
    device_name: "GN-Y201S"
    app_ver: "V3.6.1.1"
  JD:
    app_name: "京东微联"
    device_name: "GN-Y201J"
    app_ver: "V4.4.0 build:57371"
  HW:
    app_name: "智能家居"
    device_name: "GN-Y201H"
    app_ver: "V1.0.5.307"
# 手机型号及待运行APP
phone_name:
  b9388cbb:
    app: 'JD'
    mac:
    phone_module: '小米5'
  8c710f0a2007635ea8d1124575a10038e7655c6e:
    app: 'JD'
    phone_module: 'iphone 6s'
  85GABMN9UDD2:
    app: 'AL'
    phone_module: '魅族MX5'
  8681-M02-0xa0a151df:
    app: 'JD'
    phone_module: '360奇酷'
  1b010b2e0d07c07aba0490d20056ff6295ce727b:
    app: 'JD'
    phone_module: 'iphone 5s'
  6910ec366b7e396410c2be813bff57ef1c9ccc7e:
    app: 'JD'
    phone_device: 'iphone 6sp'
  54a9608b:
    app: 'AL'
    phone_module: 'vivo Y51A'
  ZTEC880U:
    app: 'JD'
    phone_module: '中兴 C880U'

