0:
  CheckLogName:
    lEcheck_flag_0: [power on, true]
    lEcheck_flag_1: [power off, false]
    lEcheck_flag_2: ['', false]
    lEcheck_flag_3: ['', false]
    lEcheck_flag_4: ['', false]
    lEcheck_flag_5: ['', false]
    lEcheck_flag_6: ['', false]
    lEcheck_flag_7: ['', false]
    lEcheck_flag_8: ['', false]
    lEcheck_flag_9: ['', false]
  DeviceParm:
    cBcom: [COM7]
    ckBonoff: [false]
    lEbaud: ['115200']
    lEbinVer: [1.0.0]
    lEdevice_model: [Y201J]
    lEfeedid: ['147969533829058057']
    lEfile_path: ["D:\\\u8FD0\u884C\u65E5\u5FD7"]
    lEmac: ['4666']
    lEmail: [1045373828@QQ.COM]
    lEssid: [IOT-CeShiCheng]
  State:
    Select: [2]
1:
  CheckLogName:
    lEcheck_flag_0: ['', false]
    lEcheck_flag_1: ['', false]
    lEcheck_flag_2: ['', false]
    lEcheck_flag_3: ['', false]
    lEcheck_flag_4: ['', false]
    lEcheck_flag_5: ['', false]
    lEcheck_flag_6: ['', false]
    lEcheck_flag_7: ['', false]
    lEcheck_flag_8: ['', false]
    lEcheck_flag_9: ['', false]
  DeviceParm:
    cBcom: [COM5]
    ckBonoff: [false]
    lEbaud: ['']
    lEbinVer: ['']
    lEdevice_model: ['']
    lEfeedid: ['']
    lEfile_path: ['']
    lEmac: ['1234']
    lEmail: ['']
    lEssid: ['']
  State:
    Select: [0]
2:
  CheckLogName:
    lEcheck_flag_0: ['', false]
    lEcheck_flag_1: ['', false]
    lEcheck_flag_2: ['', false]
    lEcheck_flag_3: ['', false]
    lEcheck_flag_4: ['', false]
    lEcheck_flag_5: ['', false]
    lEcheck_flag_6: ['', false]
    lEcheck_flag_7: ['', false]
    lEcheck_flag_8: ['', false]
    lEcheck_flag_9: ['', false]
  DeviceParm:
    cBcom: [COM1]
    ckBonoff: [false]
    lEbaud: ['']
    lEbinVer: ['']
    lEdevice_model: ['']
    lEfeedid: ['']
    lEfile_path: ['']
    lEmac: ['']
    lEmail: ['']
    lEssid: ['']
  State:
    Select: [0]
3:
  CheckLogName:
    lEcheck_flag_0: ['', false]
    lEcheck_flag_1: ['', false]
    lEcheck_flag_2: ['', false]
    lEcheck_flag_3: ['', false]
    lEcheck_flag_4: ['', false]
    lEcheck_flag_5: ['', false]
    lEcheck_flag_6: ['', false]
    lEcheck_flag_7: ['', false]
    lEcheck_flag_8: ['', false]
    lEcheck_flag_9: ['', false]
  DeviceParm:
    cBcom: [COM1]
    ckBonoff: [false]
    lEbaud: ['']
    lEbinVer: ['']
    lEdevice_model: ['']
    lEfeedid: ['']
    lEfile_path: ['']
    lEmac: ['']
    lEmail: ['']
    lEssid: ['']
  State:
    Select: [0]
4:
  CheckLogName:
    lEcheck_flag_0: ['', false]
    lEcheck_flag_1: ['', false]
    lEcheck_flag_2: ['', false]
    lEcheck_flag_3: ['', false]
    lEcheck_flag_4: ['', false]
    lEcheck_flag_5: ['', false]
    lEcheck_flag_6: ['', false]
    lEcheck_flag_7: ['', false]
    lEcheck_flag_8: ['', false]
    lEcheck_flag_9: ['', false]
  DeviceParm:
    cBcom: [COM1]
    ckBonoff: [false]
    lEbaud: ['']
    lEbinVer: ['']
    lEdevice_model: ['']
    lEfeedid: ['']
    lEfile_path: ['']
    lEmac: ['']
    lEmail: ['']
    lEssid: ['']
  State:
    Select: [0]
5:
  CheckLogName:
    lEcheck_flag_0: ['', false]
    lEcheck_flag_1: ['', false]
    lEcheck_flag_2: ['', false]
    lEcheck_flag_3: ['', false]
    lEcheck_flag_4: ['', false]
    lEcheck_flag_5: ['', false]
    lEcheck_flag_6: ['', false]
    lEcheck_flag_7: ['', false]
    lEcheck_flag_8: ['', false]
    lEcheck_flag_9: ['', false]
  DeviceParm:
    cBcom: [COM1]
    ckBonoff: [false]
    lEbaud: ['']
    lEbinVer: ['']
    lEdevice_model: ['']
    lEfeedid: ['']
    lEfile_path: ['']
    lEmac: ['']
    lEmail: ['']
    lEssid: ['']
  State:
    Select: [0]
6:
  CheckLogName:
    lEcheck_flag_0: ['', false]
    lEcheck_flag_1: ['', false]
    lEcheck_flag_2: ['', false]
    lEcheck_flag_3: ['', false]
    lEcheck_flag_4: ['', false]
    lEcheck_flag_5: ['', false]
    lEcheck_flag_6: ['', false]
    lEcheck_flag_7: ['', false]
    lEcheck_flag_8: ['', false]
    lEcheck_flag_9: ['', false]
  DeviceParm:
    cBcom: [COM1]
    ckBonoff: [false]
    lEbaud: ['']
    lEbinVer: ['']
    lEdevice_model: ['']
    lEfeedid: ['']
    lEfile_path: ['']
    lEmac: ['']
    lEmail: ['']
    lEssid: ['']
  State:
    Select: [0]
7:
  CheckLogName:
    lEcheck_flag_0: ['', false]
    lEcheck_flag_1: ['', false]
    lEcheck_flag_2: ['', false]
    lEcheck_flag_3: ['', false]
    lEcheck_flag_4: ['', false]
    lEcheck_flag_5: ['', false]
    lEcheck_flag_6: ['', false]
    lEcheck_flag_7: ['', false]
    lEcheck_flag_8: ['', false]
    lEcheck_flag_9: ['', false]
  DeviceParm:
    cBcom: [COM1]
    ckBonoff: [false]
    lEbaud: ['']
    lEbinVer: ['']
    lEdevice_model: ['']
    lEfeedid: ['']
    lEfile_path: ['']
    lEmac: ['']
    lEmail: ['']
    lEssid: ['']
  State:
    Select: [0]
8:
  CheckLogName:
    lEcheck_flag_0: ['', false]
    lEcheck_flag_1: ['', false]
    lEcheck_flag_2: ['', false]
    lEcheck_flag_3: ['', false]
    lEcheck_flag_4: ['', false]
    lEcheck_flag_5: ['', false]
    lEcheck_flag_6: ['', false]
    lEcheck_flag_7: ['', false]
    lEcheck_flag_8: ['', false]
    lEcheck_flag_9: ['', false]
  DeviceParm:
    cBcom: [COM1]
    ckBonoff: [false]
    lEbaud: ['']
    lEbinVer: ['']
    lEdevice_model: ['']
    lEfeedid: ['']
    lEfile_path: ['']
    lEmac: ['']
    lEmail: ['']
    lEssid: ['']
  State:
    Select: [0]
9:
  CheckLogName:
    lEcheck_flag_0: ['', false]
    lEcheck_flag_1: ['', false]
    lEcheck_flag_2: ['', false]
    lEcheck_flag_3: ['', false]
    lEcheck_flag_4: ['', false]
    lEcheck_flag_5: ['', false]
    lEcheck_flag_6: ['', false]
    lEcheck_flag_7: ['', false]
    lEcheck_flag_8: ['', false]
    lEcheck_flag_9: ['', false]
  DeviceParm:
    cBcom: [COM1]
    ckBonoff: [false]
    lEbaud: ['']
    lEbinVer: ['']
    lEdevice_model: ['']
    lEfeedid: ['']
    lEfile_path: ['']
    lEmac: ['']
    lEmail: ['']
    lEssid: ['']
  State:
    Select: [0]
10:
  CheckLogName:
    lEcheck_flag_0: ['', false]
    lEcheck_flag_1: ['', false]
    lEcheck_flag_2: ['', false]
    lEcheck_flag_3: ['', false]
    lEcheck_flag_4: ['', false]
    lEcheck_flag_5: ['', false]
    lEcheck_flag_6: ['', false]
    lEcheck_flag_7: ['', false]
    lEcheck_flag_8: ['', false]
    lEcheck_flag_9: ['', false]
  DeviceParm:
    cBcom: [COM1]
    ckBonoff: [false]
    lEbaud: ['']
    lEbinVer: ['']
    lEdevice_model: ['']
    lEfeedid: ['']
    lEfile_path: ['']
    lEmac: ['']
    lEmail: ['']
    lEssid: ['']
  State:
    Select: [0]
11:
  CheckLogName:
    lEcheck_flag_0: ['', false]
    lEcheck_flag_1: ['', false]
    lEcheck_flag_2: ['', false]
    lEcheck_flag_3: ['', false]
    lEcheck_flag_4: ['', false]
    lEcheck_flag_5: ['', false]
    lEcheck_flag_6: ['', false]
    lEcheck_flag_7: ['', false]
    lEcheck_flag_8: ['', false]
    lEcheck_flag_9: ['', false]
  DeviceParm:
    cBcom: [COM1]
    ckBonoff: [false]
    lEbaud: ['']
    lEbinVer: ['']
    lEdevice_model: ['']
    lEfeedid: ['']
    lEfile_path: ['']
    lEmac: ['']
    lEmail: ['']
    lEssid: ['']
  State:
    Select: [0]
12:
  CheckLogName:
    lEcheck_flag_0: ['', false]
    lEcheck_flag_1: ['', false]
    lEcheck_flag_2: ['', false]
    lEcheck_flag_3: ['', false]
    lEcheck_flag_4: ['', false]
    lEcheck_flag_5: ['', false]
    lEcheck_flag_6: ['', false]
    lEcheck_flag_7: ['', false]
    lEcheck_flag_8: ['', false]
    lEcheck_flag_9: ['', false]
  DeviceParm:
    cBcom: [COM1]
    ckBonoff: [false]
    lEbaud: ['']
    lEbinVer: ['']
    lEdevice_model: ['']
    lEfeedid: ['']
    lEfile_path: ['']
    lEmac: ['']
    lEmail: ['']
    lEssid: ['']
  State:
    Select: [0]
