# 打开APP超时时间
open_app_timeout: 60
# 搜索设备超时时间
search_device_timeout: 60
# 操作响应超时时间
request_timeout: 30
# 离线恢复超时时间
offline_recovery_timeout: 10
# 程序操作等待时间
operate_wait_time: 0.1
# 待添加的设备Mac
MAC: 'C4-11-E0-00-46-26'
# Mac地址列表选取标志位
mac_choose_flag: 1
# 错误密码
err_pwd: '31323334353637383930'
# 登录密码
login_pwd: 6368656e6768616f
# 新密码
new_pwd: 6368656e6768616f31
# 旧密码
old_pwd: 6368656e6768616f
# 用户名
user_name: '3138303432303738393237'
# wifi密码
wifi_pwd: 696f74313233343536
# 待选择App
App:
  GN: [com.iotbull.android.superapp, com.iotbull.android.superapp.activitys.regist_login.SplashActivity]
  JD: [com.jd.smart, com.jd.smart.activity.LoadingActivity]
# Toast消息
Toast:
  login_password_mistake: [40, 1570, 1040, 1750]